#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GithubXamarin.Droid.Resource", IsApplication=true)]

namespace GithubXamarin.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int search_array = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorPrimary = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimaryDark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int colorPrimaryLight = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int colorPrimarySuperDark = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int defaultText = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int divider = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int primaryText = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int secondaryText = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int splash_background = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int white = 2130837514;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int default_horizontal_padding = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int default_vertical_padding = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int drawer_width = 2130903042;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int background = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int background_splash = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ic_bug_report_black_24dp = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int ic_build_black_24dp = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ic_create_black_24dp = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int ic_home_black_24dp = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int ic_inbox_black_24dp = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int ic_launcher = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int ic_notifications_black_24dp = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int ic_notifications_none_black_24dp = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int ic_offline_pin_black_24dp = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int ic_priority_high_black_24dp = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int ic_refresh_white_24dp = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int ic_search_black_24dp = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int ic_search_white_24dp = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int ic_send_white_24dp = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int ic_settings_black_24dp = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int ic_star_black_24dp = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int ic_stat_newstorelogo_scale_400 = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int ic_sync_black_24dp = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int splash = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int web_hi_res_512 = 2130968597;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050007
			public const int action_search = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int appbar = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int button1 = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int button15 = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int button2 = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int button3 = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int button4 = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int button5 = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int button6 = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int button7 = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int button8 = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int card1 = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int card2 = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int closedIssuesLayout = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int content_frame = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int drawer_layout = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int editText1 = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int email = 2131034136;
			
			// aapt resource value: 0x7F050000
			public const int EventsItemWrapperLayout = 2131034112;
			
			// aapt resource value: 0x7F050019
			public const int events_refresh = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int file_edit = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int file_refresh = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int fontAwesome1 = 2131034140;
			
			// aapt resource value: 0x7F050001
			public const int GistItemWrapperLayout = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int GistsItemWrapperLayout = 2131034114;
			
			// aapt resource value: 0x7F05001D
			public const int help_menu = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int issueCommentsLabelContainer = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int issueLabelContainer = 2131034143;
			
			// aapt resource value: 0x7F050003
			public const int IssuesItemWrapperLayout = 2131034115;
			
			// aapt resource value: 0x7F050022
			public const int issuesLayout = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int issuesTabLayout = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int issues_refresh = 2131034148;
			
			// aapt resource value: 0x7F050020
			public const int issue_edit = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int issue_refresh = 2131034145;
			
			// aapt resource value: 0x7F050025
			public const int linearLayout1 = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int login_webview = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int main_menu = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int nav_gists = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int nav_home = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int nav_issues = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int nav_notifications = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int nav_repositories = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int nav_settings = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int nav_view = 2131034158;
			
			// aapt resource value: 0x7F050004
			public const int NotificationsItemWrapperLayout = 2131034116;
			
			// aapt resource value: 0x7F05002F
			public const int notifications_mark_all_read = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int notifications_refresh = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int profile_image = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int repoLayout = 2131034162;
			
			// aapt resource value: 0x7F050005
			public const int RepositoriesItemWrapperLayout = 2131034117;
			
			// aapt resource value: 0x7F050034
			public const int repositories_add = 2131034164;
			
			// aapt resource value: 0x7F050035
			public const int repositories_refresh = 2131034165;
			
			// aapt resource value: 0x7F050036
			public const int repository_add_issue = 2131034166;
			
			// aapt resource value: 0x7F050037
			public const int repository_contents_add = 2131034167;
			
			// aapt resource value: 0x7F050038
			public const int repository_contents_refresh = 2131034168;
			
			// aapt resource value: 0x7F050039
			public const int repository_edit = 2131034169;
			
			// aapt resource value: 0x7F05003A
			public const int repository_refresh = 2131034170;
			
			// aapt resource value: 0x7F050033
			public const int repoTabLayout = 2131034163;
			
			// aapt resource value: 0x7F05003B
			public const int settingsLayout = 2131034171;
			
			// aapt resource value: 0x7F05003C
			public const int settingsTabLayout = 2131034172;
			
			// aapt resource value: 0x7F05003D
			public const int settingsUsersLayout = 2131034173;
			
			// aapt resource value: 0x7F05003E
			public const int starredRepoLayout = 2131034174;
			
			// aapt resource value: 0x7F05003F
			public const int textView1 = 2131034175;
			
			// aapt resource value: 0x7F050040
			public const int textView2 = 2131034176;
			
			// aapt resource value: 0x7F050041
			public const int textView3 = 2131034177;
			
			// aapt resource value: 0x7F050042
			public const int textView6 = 2131034178;
			
			// aapt resource value: 0x7F050043
			public const int title_layout = 2131034179;
			
			// aapt resource value: 0x7F050044
			public const int toggleButton1 = 2131034180;
			
			// aapt resource value: 0x7F050045
			public const int toggleButton2 = 2131034181;
			
			// aapt resource value: 0x7F050046
			public const int toolbar = 2131034182;
			
			// aapt resource value: 0x7F050047
			public const int toolbar_title = 2131034183;
			
			// aapt resource value: 0x7F05004A
			public const int username = 2131034186;
			
			// aapt resource value: 0x7F050006
			public const int UsersItemWrapperLayout = 2131034118;
			
			// aapt resource value: 0x7F05004B
			public const int users_refresh = 2131034187;
			
			// aapt resource value: 0x7F050048
			public const int user_edit = 2131034184;
			
			// aapt resource value: 0x7F050049
			public const int user_refresh = 2131034185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060015
			public const int contents_item_template = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int drawer_header = 2131099670;
			
			// aapt resource value: 0x7F060000
			public const int EventsView = 2131099648;
			
			// aapt resource value: 0x7F060017
			public const int events_item_template = 2131099671;
			
			// aapt resource value: 0x7F060001
			public const int FileView = 2131099649;
			
			// aapt resource value: 0x7F060003
			public const int GistsView = 2131099651;
			
			// aapt resource value: 0x7F060019
			public const int gists_item_template = 2131099673;
			
			// aapt resource value: 0x7F060002
			public const int GistView = 2131099650;
			
			// aapt resource value: 0x7F060018
			public const int gist_item_template = 2131099672;
			
			// aapt resource value: 0x7F060005
			public const int IssuesView = 2131099653;
			
			// aapt resource value: 0x7F06001B
			public const int issues_item_template = 2131099675;
			
			// aapt resource value: 0x7F060004
			public const int IssueView = 2131099652;
			
			// aapt resource value: 0x7F06001A
			public const int issue_comments_item_template = 2131099674;
			
			// aapt resource value: 0x7F06001C
			public const int labels_item_template = 2131099676;
			
			// aapt resource value: 0x7F060006
			public const int LoginView = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int Main = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int NewFileView = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int NewIssueView = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int NewRepositoryView = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int NewUserView = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int NotificationsView = 2131099660;
			
			// aapt resource value: 0x7F06001D
			public const int notifications_item_template = 2131099677;
			
			// aapt resource value: 0x7F06000D
			public const int RepositoriesView = 2131099661;
			
			// aapt resource value: 0x7F06001E
			public const int repositories_item_template = 2131099678;
			
			// aapt resource value: 0x7F06000E
			public const int RepositoryContentsView = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int RepositoryView = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int SearchView = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int SettingsView = 2131099665;
			
			// aapt resource value: 0x7F06001F
			public const int toolbar = 2131099679;
			
			// aapt resource value: 0x7F060012
			public const int UserOnboarding = 2131099666;
			
			// aapt resource value: 0x7F060014
			public const int UsersView = 2131099668;
			
			// aapt resource value: 0x7F060020
			public const int users_item_template = 2131099680;
			
			// aapt resource value: 0x7F060013
			public const int UserView = 2131099667;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F070000
			public const int drawer_item_color = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int events_menu = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int file_menu = 2131165186;
			
			// aapt resource value: 0x7F070004
			public const int issues_menu = 2131165188;
			
			// aapt resource value: 0x7F070003
			public const int issue_menu = 2131165187;
			
			// aapt resource value: 0x7F070005
			public const int item_search = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int nav_menu = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int notifications_menu = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int repositories_menu = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int repository_contents_menu = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int repository_menu = 2131165194;
			
			// aapt resource value: 0x7F07000C
			public const int users_menu = 2131165196;
			
			// aapt resource value: 0x7F07000B
			public const int user_menu = 2131165195;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int ApplicationName = 2131230720;
			
			// aapt resource value: 0x7F080003
			public const int drawer_close = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int drawer_open = 2131230724;
			
			// aapt resource value: 0x7F080001
			public const int Empty = 2131230721;
			
			// aapt resource value: 0x7F080005
			public const int fa_bell = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int fa_check = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int fa_code = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int fa_code_fork = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int fa_comment = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int fa_exclamation = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int fa_file_code = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int fa_hdd = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int fa_home = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int fa_refresh = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int fa_star = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int fa_users = 2131230736;
			
			// aapt resource value: 0x7F080002
			public const int Hello = 2131230722;
			
			// aapt resource value: 0x7F080011
			public const int search_array = 2131230737;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int MyTheme = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int MyTheme_Base = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int MyTheme_Splash = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int Theme = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int Theme_AppCompat = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int Theme_AppCompat_Light = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int Theme_AppCompat_Light_NoActionBar = 2131296262;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
